#use the openjdk 17 image as the base image
FROM openjdk:17

#Create a new app directory for my application files
RUN mkdir /app

#COpy the app files from host machine to image filesystem
COPY src/main/java/ /app